config/routes.rb
Rails.application.routes.draw do
  resources :group_rules
  resources :group_rule_details
  resources :rules
  resources :rule_types
  resources :node_messages
  resources :node_message_parrameters
  resources :value_types
  resources :node_message_types
  resources :node_types
  resources :nodes
  resources :iotonservers
  resources :userroles
  resources :permissionviewroles
  resources :permissionviews
  resources :permissions
  resources :viewmenus
  resources :roles
  get 'countries/new'

  get 'staticpages/mychart'

  root 'pages#home'

  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/client_home', to: 'pages#client_home'

  resources :clients
  resources :departments
  resources :sites
  namespace :api, :defaults => {:format => 'json'} do
    resources :people
  end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :countries, only: [:new, :create]
  get '/countries/new', to: 'countries#new'
  get '/staticpages/mychart',   to: 'staticpages#mychart'
  get '/staticpages/statchart',   to: 'staticpages#statchart'
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :departments
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :client
  has_many :sites
end

app/models/group_rule.rb
class GroupRule < ActiveRecord::Base
end

app/models/iotonserver.rb
class Iotonserver < ActiveRecord::Base
  belongs_to :site
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :node_type
end

app/models/node_message.rb
class NodeMessage < ActiveRecord::Base
end

app/models/node_message_type.rb
class NodeMessageType < ActiveRecord::Base
end

app/models/node_type.rb
class NodeType < ActiveRecord::Base
  
end

app/models/people.rb
class People < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/rule.rb
class Rule < ActiveRecord::Base
end

app/models/rule_type.rb
class RuleType < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :department
  has_many :iotonservers
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
    uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  before_save { self.email = email.downcase }

  #def generate_api_key
   # loop do
  #    token = SecureRandom.base64.tr('+/=', 'Qrt')
  #    break token unless User.exists?(api_key: token).any?
  #  end
  #end

  #before_create do |doc|
  #  doc.api_key = doc.generate_api_key
  #end
end

app/models/userrole.rb
class Userrole < ActiveRecord::Base
  belongs_to :role
  belongs_to :user
end

app/models/value_type.rb
class ValueType < ActiveRecord::Base
end

app/models/viewmenu.rb
class Viewmenu < ActiveRecord::Base
end

app/controllers/node_messages_controller.rb
class NodeMessagesController < ApplicationController
  before_action :set_node_message, only: [:show, :edit, :update, :destroy]

  # GET /node_messages
  # GET /node_messages.json
  def index
    @node_messages = NodeMessage.all
  end

  # GET /node_messages/1
  # GET /node_messages/1.json
  def show
  end

  # GET /node_messages/new
  def new
    @node_message = NodeMessage.new
  end

  # GET /node_messages/1/edit
  def edit
  end

  # POST /node_messages
  # POST /node_messages.json
  def create
    @node_message = NodeMessage.new(node_message_params)

    respond_to do |format|
      if @node_message.save
        format.html { redirect_to @node_message, notice: 'Node message was successfully created.' }
        format.json { render :show, status: :created, location: @node_message }
      else
        format.html { render :new }
        format.json { render json: @node_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /node_messages/1
  # PATCH/PUT /node_messages/1.json
  def update
    respond_to do |format|
      if @node_message.update(node_message_params)
        format.html { redirect_to @node_message, notice: 'Node message was successfully updated.' }
        format.json { render :show, status: :ok, location: @node_message }
      else
        format.html { render :edit }
        format.json { render json: @node_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /node_messages/1
  # DELETE /node_messages/1.json
  def destroy
    @node_message.destroy
    respond_to do |format|
      format.html { redirect_to node_messages_url, notice: 'Node message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node_message
      @node_message = NodeMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_message_params
      params.require(:node_message).permit(:name, :node_type_id, :node_message_type_id, :downloaded)
    end
end

app/helpers/node_messages_helper.rb
module NodeMessagesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/node_messages/_form.html.erb
<%= form_for(@node_message) do |f| %>
  <% if @node_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node_message.errors.count, "error") %> prohibited this node_message from being saved:</h2>

      <ul>
      <% @node_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :node_type_id %><br>
    <%= f.number_field :node_type_id %>
  </div>
  <div class="field">
    <%= f.label :node_message_type_id %><br>
    <%= f.number_field :node_message_type_id %>
  </div>
  <div class="field">
    <%= f.label :downloaded %><br>
    <%= f.check_box :downloaded %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/node_messages/edit.html.erb
<h1>Editing Node Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @node_message %> |
<%= link_to 'Back', node_messages_path %>

app/views/node_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Node Messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Node type</th>
      <th>Node message type</th>
      <th>Downloaded</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @node_messages.each do |node_message| %>
      <tr>
        <td><%= node_message.name %></td>
        <td><%= node_message.node_type_id %></td>
        <td><%= node_message.node_message_type_id %></td>
        <td><%= node_message.downloaded %></td>
        <td><%= link_to 'Show', node_message %></td>
        <td><%= link_to 'Edit', edit_node_message_path(node_message) %></td>
        <td><%= link_to 'Destroy', node_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node message', new_node_message_path %>

app/views/node_messages/new.html.erb
<h1>New Node Message</h1>

<%= render 'form' %>

<%= link_to 'Back', node_messages_path %>

app/views/node_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node_message.name %>
</p>

<p>
  <strong>Node type:</strong>
  <%= @node_message.node_type_id %>
</p>

<p>
  <strong>Node message type:</strong>
  <%= @node_message.node_message_type_id %>
</p>

<p>
  <strong>Downloaded:</strong>
  <%= @node_message.downloaded %>
</p>

<%= link_to 'Edit', edit_node_message_path(@node_message) %> |
<%= link_to 'Back', node_messages_path %>