config/routes.rb
Rails.application.routes.draw do
  resources :group_rules
  resources :group_rule_details
  resources :rules
  resources :rule_types
  resources :node_messages
  resources :node_message_parrameters
  resources :value_types
  resources :node_message_types
  resources :node_types
  resources :nodes
  resources :iotonservers
  resources :userroles
  resources :permissionviewroles
  resources :permissionviews
  resources :permissions
  resources :viewmenus
  resources :roles
  get 'countries/new'

  get 'staticpages/mychart'

  root 'pages#home'

  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/client_home', to: 'pages#client_home'

  resources :clients
  resources :departments
  resources :sites
  namespace :api, :defaults => {:format => 'json'} do
    resources :people
  end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :countries, only: [:new, :create]
  get '/countries/new', to: 'countries#new'
  get '/staticpages/mychart',   to: 'staticpages#mychart'
  get '/staticpages/statchart',   to: 'staticpages#statchart'
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :departments
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :client
  has_many :sites
end

app/models/group_rule.rb
class GroupRule < ActiveRecord::Base
end

app/models/iotonserver.rb
class Iotonserver < ActiveRecord::Base
  belongs_to :site
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :node_type
end

app/models/node_message.rb
class NodeMessage < ActiveRecord::Base
end

app/models/node_type.rb
class NodeType < ActiveRecord::Base
  
end

app/models/people.rb
class People < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/rule.rb
class Rule < ActiveRecord::Base
end

app/models/rule_type.rb
class RuleType < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :department
  has_many :iotonservers
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
    uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  before_save { self.email = email.downcase }

  #def generate_api_key
   # loop do
  #    token = SecureRandom.base64.tr('+/=', 'Qrt')
  #    break token unless User.exists?(api_key: token).any?
  #  end
  #end

  #before_create do |doc|
  #  doc.api_key = doc.generate_api_key
  #end
end

app/models/userrole.rb
class Userrole < ActiveRecord::Base
  belongs_to :role
  belongs_to :user
end

app/models/value_type.rb
class ValueType < ActiveRecord::Base
end

app/models/viewmenu.rb
class Viewmenu < ActiveRecord::Base
end

app/controllers/value_types_controller.rb
class ValueTypesController < ApplicationController
  before_action :set_value_type, only: [:show, :edit, :update, :destroy]

  # GET /value_types
  # GET /value_types.json
  def index
    @value_types = ValueType.all
  end

  # GET /value_types/1
  # GET /value_types/1.json
  def show
  end

  # GET /value_types/new
  def new
    @value_type = ValueType.new
  end

  # GET /value_types/1/edit
  def edit
  end

  # POST /value_types
  # POST /value_types.json
  def create
    @value_type = ValueType.new(value_type_params)

    respond_to do |format|
      if @value_type.save
        format.html { redirect_to @value_type, notice: 'Value type was successfully created.' }
        format.json { render :show, status: :created, location: @value_type }
      else
        format.html { render :new }
        format.json { render json: @value_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /value_types/1
  # PATCH/PUT /value_types/1.json
  def update
    respond_to do |format|
      if @value_type.update(value_type_params)
        format.html { redirect_to @value_type, notice: 'Value type was successfully updated.' }
        format.json { render :show, status: :ok, location: @value_type }
      else
        format.html { render :edit }
        format.json { render json: @value_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /value_types/1
  # DELETE /value_types/1.json
  def destroy
    @value_type.destroy
    respond_to do |format|
      format.html { redirect_to value_types_url, notice: 'Value type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_value_type
      @value_type = ValueType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def value_type_params
      params.require(:value_type).permit(:name, :description, :downloaded)
    end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/value_types_helper.rb
module ValueTypesHelper
end

app/views/value_types/_form.html.erb
<%= form_for(@value_type) do |f| %>
  <% if @value_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@value_type.errors.count, "error") %> prohibited this value_type from being saved:</h2>

      <ul>
      <% @value_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :downloaded %><br>
    <%= f.check_box :downloaded %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/value_types/edit.html.erb
<h1>Editing Value Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @value_type %> |
<%= link_to 'Back', value_types_path %>

app/views/value_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Value Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Downloaded</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @value_types.each do |value_type| %>
      <tr>
        <td><%= value_type.name %></td>
        <td><%= value_type.description %></td>
        <td><%= value_type.downloaded %></td>
        <td><%= link_to 'Show', value_type %></td>
        <td><%= link_to 'Edit', edit_value_type_path(value_type) %></td>
        <td><%= link_to 'Destroy', value_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Value type', new_value_type_path %>

app/views/value_types/new.html.erb
<h1>New Value Type</h1>

<%= render 'form' %>

<%= link_to 'Back', value_types_path %>

app/views/value_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @value_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @value_type.description %>
</p>

<p>
  <strong>Downloaded:</strong>
  <%= @value_type.downloaded %>
</p>

<%= link_to 'Edit', edit_value_type_path(@value_type) %> |
<%= link_to 'Back', value_types_path %>