config/routes.rb
Rails.application.routes.draw do
  resources :group_rules
  resources :group_rule_details
  resources :rules
  resources :rule_types
  resources :node_messages
  resources :node_message_parrameters
  resources :value_types
  resources :node_message_types
  resources :node_types
  resources :nodes
  resources :iotonservers
  resources :userroles
  resources :permissionviewroles
  resources :permissionviews
  resources :permissions
  resources :viewmenus
  resources :roles
  get 'countries/new'

  get 'staticpages/mychart'

  root 'pages#home'

  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/client_home', to: 'pages#client_home'

  resources :clients
  resources :departments
  resources :sites
  namespace :api, :defaults => {:format => 'json'} do
    resources :people
  end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :countries, only: [:new, :create]
  get '/countries/new', to: 'countries#new'
  get '/staticpages/mychart',   to: 'staticpages#mychart'
  get '/staticpages/statchart',   to: 'staticpages#statchart'
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :departments
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :client
  has_many :sites
end

app/models/group_rule.rb
class GroupRule < ActiveRecord::Base
end

app/models/iotonserver.rb
class Iotonserver < ActiveRecord::Base
  belongs_to :site
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :node_type
end

app/models/node_message.rb
class NodeMessage < ActiveRecord::Base
end

app/models/node_type.rb
class NodeType < ActiveRecord::Base
  
end

app/models/people.rb
class People < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/permissionview.rb
class Permissionview < ActiveRecord::Base
  belongs_to :permission
  belongs_to :viewmenu
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/rule.rb
class Rule < ActiveRecord::Base
end

app/models/rule_type.rb
class RuleType < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :department
  has_many :iotonservers
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
    uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  before_save { self.email = email.downcase }

  #def generate_api_key
   # loop do
  #    token = SecureRandom.base64.tr('+/=', 'Qrt')
  #    break token unless User.exists?(api_key: token).any?
  #  end
  #end

  #before_create do |doc|
  #  doc.api_key = doc.generate_api_key
  #end
end

app/models/userrole.rb
class Userrole < ActiveRecord::Base
  belongs_to :role
  belongs_to :user
end

app/models/value_type.rb
class ValueType < ActiveRecord::Base
end

app/models/viewmenu.rb
class Viewmenu < ActiveRecord::Base
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @client = Client.find(session[:client_id])
	  @department = Department.find(session[:department_id])
    @site = Site.find(session[:site_id])
    @iotonserver = Iotonserver.find(session[:iotonserver_id])
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @client = Client.find(session[:client_id])
	  @department = Department.find(session[:department_id])
    @site = Site.find(session[:site_id])
    @iotonserver = Iotonserver.find(session[:iotonserver_id])
  end

  # GET /nodes/new
  def new
    @client = Client.find(session[:client_id])
	  @department = Department.find(session[:department_id])
    @site = Site.find(session[:site_id])
    @iotonserver = Iotonserver.find(session[:iotonserver_id])
    @node = Node.new
    @node_type = NodeType.all
  end

  # GET /nodes/1/edit
  def edit
    @client = Client.find(session[:client_id])
	  @department = Department.find(session[:department_id])
    @site = Site.find(session[:site_id])
    @iotonserver = Iotonserver.find(session[:iotonserver_id])
    @node_types = Node_type.all
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)
    @client = Client.find(session[:client_id])
	  @department = Department.find(session[:department_id])
    @site = Site.find(session[:site_id])
    @iotonserver = Iotonserver.find(session[:iotonserver_id])
    @node.downloaded = false
    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    @client = Client.find(session[:client_id])
	  @department = Department.find(session[:department_id])
    @site = Site.find(session[:site_id])
    @iotonserver = Iotonserver.find(session[:iotonserver_id])
    @node.downloaded = false
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name, :node_type_id, :iotonserver_id, :downloaded)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/nodes/_form.html.erb
<% if @node.errors.any? %>
  <h2>The following errors prevented the node_type from getting created</h2>
  <ul>
  <% @node.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@node, :html => {class: "form-horizontal", role: "form"}) do |f| %>
	    <br>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :node_type %>
        </div>
        <div class="col-sm-8">
          <%= f.collection_select :node_type_id, @node_type, :id, :name, :prompt => "Select a node_type" , class: "form-control", autofocus: true%>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field:name, class: "form-control", placeholder: "name of node", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to nodes listing", nodes_path, class: "btn btn-xs btn-success" %> ]
    </div>
  </div>
</div>

app/views/nodes/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>System Configuration</h2></div>
    <div class="panel-body">
      <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading"><h1>Edit existing node</h1></div>
        <%= render "form" %>
      </div>
    </div>
</div>

app/views/nodes/index.html.erb
<div class="panel panel-default">
	<div class="panel-heading"><h3>[Client: <%= @client.name %>] - [Department: <%= @department.name %>] - [Site: <%= @site.name %>] - [IoToN Server: <%= @iotonserver.name %>]</h3></div>
	<div class="panel-body">
		<p>
		  <%= link_to "Create new node", new_node_path, class: "btn btn-xs btn-success" %>
		</p>
		<div class="panel panel-primary">
			<!-- Default panel contents -->
			<div class="panel-heading"><h1>Listing all nodes</h1></div>
			<table class="table">
			  <tr>

				<th>id</th>

				<th>node_type</th>

				<th>node_name</th>

				<th>downloaded</th>

			  </tr>
			  <% @nodes.each do |node| %>
				<tr>

				  <td><%= node.id %></td>

          <td><%= node.node_type.name %></td>

				  <td><%= node.name %></td>

				  <td><%= node.downloaded %></td>

				  <td><%= link_to 'Edit', edit_node_path(node), class: "btn btn-xs btn-primary" %> </td>
				  <td><%= link_to 'Delete', node_path(node), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %></td>
				  <td><%= link_to 'Back', node_path(node), class: "btn btn-xs btn-warning"  %> </td>
				</tr>
			  <% end %>
			</table>
	</div>
</div>

app/views/nodes/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>System Configuration</h2></div>
    <div class="panel-body">
      <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading"><h1>Create new node</h1></div>
        <%= render "form" %>
      </div>
    </div>
</div>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<p>
  <strong>Node type:</strong>
  <%= @node.node_type_id %>
</p>

<p>
  <strong>Iotonserver:</strong>
  <%= @node.iotonserver_id %>
</p>

<p>
  <strong>Downloaded:</strong>
  <%= @node.downloaded %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>